create table companies (
    id bigint generated by default as identity primary key,
    name varchar(255) not null,
    source_url varchar(2048),
    created_at timestamp not null,
    updated_at timestamp not null,
    constraint uk_companies_name unique (name)
);

create table tags (
    id bigint generated by default as identity primary key,
    name varchar(120) not null,
    constraint uk_tags_name unique (name)
);

create table jobs (
    id bigint generated by default as identity primary key,
    external_id varchar(255) not null,
    title varchar(500) not null,
    location varchar(500),
    description text,
    source_url varchar(2048) not null,
    remote_type varchar(120),
    seniority varchar(120),
    salary_text varchar(255),
    posted_at_text varchar(255),
    active boolean not null default true,
    company_id bigint not null,
    first_seen_at timestamp not null,
    last_seen_at timestamp not null,
    created_at timestamp not null,
    updated_at timestamp not null,
    constraint uk_jobs_external_id unique (external_id),
    constraint uk_jobs_source_url unique (source_url),
    constraint fk_jobs_company foreign key (company_id) references companies (id)
);

create table job_tags (
    job_id bigint not null,
    tag_id bigint not null,
    primary key (job_id, tag_id),
    constraint fk_job_tags_job foreign key (job_id) references jobs (id) on delete cascade,
    constraint fk_job_tags_tag foreign key (tag_id) references tags (id) on delete cascade
);

create table scrape_runs (
    id bigint generated by default as identity primary key,
    started_at timestamp not null,
    finished_at timestamp,
    status varchar(40) not null,
    retrieved_count integer not null default 0,
    created_count integer not null default 0,
    updated_count integer not null default 0,
    deactivated_count integer not null default 0,
    error_message text
);

create index idx_jobs_active on jobs (active);
create index idx_jobs_location on jobs (location);
create index idx_jobs_title on jobs (title);
create index idx_jobs_company_id on jobs (company_id);
create index idx_scrape_runs_started_at on scrape_runs (started_at);
